server:
  port: 8083

spring:
  application:
    name: role-service
  config:
    import: optional:configserver:http://localhost:8888


  # Local database configuration (fallback if Config Server not available)
  datasource:
    url: jdbc:postgresql://localhost:5432/role_db
    username: postgres
    password: PostGres123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

